# ---------- BUILD STAGE ----------
FROM maven:3.9-eclipse-temurin-21 AS build

WORKDIR /app

COPY pom.xml .
COPY src ./src

RUN mvn clean package -DskipTests


# ---------- RUNTIME STAGE ----------
FROM eclipse-temurin:21-jre

WORKDIR /app

# create non-root user (security best practice)
RUN useradd -m appuser
USER appuser

COPY --from=build app/target/weather-service-0.0.1-SNAPSHOT.jar  app.jar

EXPOSE 8081

# JVM tuning (important for k8s)
ENTRYPOINT ["java","-XX:+UseContainerSupport","-XX:MaxRAMPercentage=75.0","-jar","app.jar"]